# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gfleming/Post-Quantum-PKI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gfleming/Post-Quantum-PKI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gfleming/Post-Quantum-PKI/CMakeFiles /home/gfleming/Post-Quantum-PKI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gfleming/Post-Quantum-PKI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named round5

# Build rule for target.
round5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 round5
.PHONY : round5

# fast build rule for target.
round5/fast:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/build
.PHONY : round5/fast

#=============================================================================
# Target rules for targets named dilithium

# Build rule for target.
dilithium: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dilithium
.PHONY : dilithium

# fast build rule for target.
dilithium/fast:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/build
.PHONY : dilithium/fast

#=============================================================================
# Target rules for targets named engine_check

# Build rule for target.
engine_check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine_check
.PHONY : engine_check

# fast build rule for target.
engine_check/fast:
	$(MAKE) -f CMakeFiles/engine_check.dir/build.make CMakeFiles/engine_check.dir/build
.PHONY : engine_check/fast

#=============================================================================
# Target rules for targets named round5_engine

# Build rule for target.
round5_engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 round5_engine
.PHONY : round5_engine

# fast build rule for target.
round5_engine/fast:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/build
.PHONY : round5_engine/fast

Round5/reference/src/a_fixed.o: Round5/reference/src/a_fixed.c.o

.PHONY : Round5/reference/src/a_fixed.o

# target to build an object file
Round5/reference/src/a_fixed.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/a_fixed.c.o
.PHONY : Round5/reference/src/a_fixed.c.o

Round5/reference/src/a_fixed.i: Round5/reference/src/a_fixed.c.i

.PHONY : Round5/reference/src/a_fixed.i

# target to preprocess a source file
Round5/reference/src/a_fixed.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/a_fixed.c.i
.PHONY : Round5/reference/src/a_fixed.c.i

Round5/reference/src/a_fixed.s: Round5/reference/src/a_fixed.c.s

.PHONY : Round5/reference/src/a_fixed.s

# target to generate assembly for a file
Round5/reference/src/a_fixed.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/a_fixed.c.s
.PHONY : Round5/reference/src/a_fixed.c.s

Round5/reference/src/a_random.o: Round5/reference/src/a_random.c.o

.PHONY : Round5/reference/src/a_random.o

# target to build an object file
Round5/reference/src/a_random.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/a_random.c.o
.PHONY : Round5/reference/src/a_random.c.o

Round5/reference/src/a_random.i: Round5/reference/src/a_random.c.i

.PHONY : Round5/reference/src/a_random.i

# target to preprocess a source file
Round5/reference/src/a_random.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/a_random.c.i
.PHONY : Round5/reference/src/a_random.c.i

Round5/reference/src/a_random.s: Round5/reference/src/a_random.c.s

.PHONY : Round5/reference/src/a_random.s

# target to generate assembly for a file
Round5/reference/src/a_random.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/a_random.c.s
.PHONY : Round5/reference/src/a_random.c.s

Round5/reference/src/cca_encrypt.o: Round5/reference/src/cca_encrypt.c.o

.PHONY : Round5/reference/src/cca_encrypt.o

# target to build an object file
Round5/reference/src/cca_encrypt.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/cca_encrypt.c.o
.PHONY : Round5/reference/src/cca_encrypt.c.o

Round5/reference/src/cca_encrypt.i: Round5/reference/src/cca_encrypt.c.i

.PHONY : Round5/reference/src/cca_encrypt.i

# target to preprocess a source file
Round5/reference/src/cca_encrypt.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/cca_encrypt.c.i
.PHONY : Round5/reference/src/cca_encrypt.c.i

Round5/reference/src/cca_encrypt.s: Round5/reference/src/cca_encrypt.c.s

.PHONY : Round5/reference/src/cca_encrypt.s

# target to generate assembly for a file
Round5/reference/src/cca_encrypt.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/cca_encrypt.c.s
.PHONY : Round5/reference/src/cca_encrypt.c.s

Round5/reference/src/cpa_kem.o: Round5/reference/src/cpa_kem.c.o

.PHONY : Round5/reference/src/cpa_kem.o

# target to build an object file
Round5/reference/src/cpa_kem.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/cpa_kem.c.o
.PHONY : Round5/reference/src/cpa_kem.c.o

Round5/reference/src/cpa_kem.i: Round5/reference/src/cpa_kem.c.i

.PHONY : Round5/reference/src/cpa_kem.i

# target to preprocess a source file
Round5/reference/src/cpa_kem.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/cpa_kem.c.i
.PHONY : Round5/reference/src/cpa_kem.c.i

Round5/reference/src/cpa_kem.s: Round5/reference/src/cpa_kem.c.s

.PHONY : Round5/reference/src/cpa_kem.s

# target to generate assembly for a file
Round5/reference/src/cpa_kem.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/cpa_kem.c.s
.PHONY : Round5/reference/src/cpa_kem.c.s

Round5/reference/src/drbg.o: Round5/reference/src/drbg.c.o

.PHONY : Round5/reference/src/drbg.o

# target to build an object file
Round5/reference/src/drbg.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/drbg.c.o
.PHONY : Round5/reference/src/drbg.c.o

Round5/reference/src/drbg.i: Round5/reference/src/drbg.c.i

.PHONY : Round5/reference/src/drbg.i

# target to preprocess a source file
Round5/reference/src/drbg.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/drbg.c.i
.PHONY : Round5/reference/src/drbg.c.i

Round5/reference/src/drbg.s: Round5/reference/src/drbg.c.s

.PHONY : Round5/reference/src/drbg.s

# target to generate assembly for a file
Round5/reference/src/drbg.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/drbg.c.s
.PHONY : Round5/reference/src/drbg.c.s

Round5/reference/src/little_endian.o: Round5/reference/src/little_endian.c.o

.PHONY : Round5/reference/src/little_endian.o

# target to build an object file
Round5/reference/src/little_endian.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/little_endian.c.o
.PHONY : Round5/reference/src/little_endian.c.o

Round5/reference/src/little_endian.i: Round5/reference/src/little_endian.c.i

.PHONY : Round5/reference/src/little_endian.i

# target to preprocess a source file
Round5/reference/src/little_endian.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/little_endian.c.i
.PHONY : Round5/reference/src/little_endian.c.i

Round5/reference/src/little_endian.s: Round5/reference/src/little_endian.c.s

.PHONY : Round5/reference/src/little_endian.s

# target to generate assembly for a file
Round5/reference/src/little_endian.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/little_endian.c.s
.PHONY : Round5/reference/src/little_endian.c.s

Round5/reference/src/misc.o: Round5/reference/src/misc.c.o

.PHONY : Round5/reference/src/misc.o

# target to build an object file
Round5/reference/src/misc.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/misc.c.o
.PHONY : Round5/reference/src/misc.c.o

Round5/reference/src/misc.i: Round5/reference/src/misc.c.i

.PHONY : Round5/reference/src/misc.i

# target to preprocess a source file
Round5/reference/src/misc.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/misc.c.i
.PHONY : Round5/reference/src/misc.c.i

Round5/reference/src/misc.s: Round5/reference/src/misc.c.s

.PHONY : Round5/reference/src/misc.s

# target to generate assembly for a file
Round5/reference/src/misc.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/misc.c.s
.PHONY : Round5/reference/src/misc.c.s

Round5/reference/src/nist_rng.o: Round5/reference/src/nist_rng.c.o

.PHONY : Round5/reference/src/nist_rng.o

# target to build an object file
Round5/reference/src/nist_rng.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/nist_rng.c.o
.PHONY : Round5/reference/src/nist_rng.c.o

Round5/reference/src/nist_rng.i: Round5/reference/src/nist_rng.c.i

.PHONY : Round5/reference/src/nist_rng.i

# target to preprocess a source file
Round5/reference/src/nist_rng.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/nist_rng.c.i
.PHONY : Round5/reference/src/nist_rng.c.i

Round5/reference/src/nist_rng.s: Round5/reference/src/nist_rng.c.s

.PHONY : Round5/reference/src/nist_rng.s

# target to generate assembly for a file
Round5/reference/src/nist_rng.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/nist_rng.c.s
.PHONY : Round5/reference/src/nist_rng.c.s

Round5/reference/src/pack.o: Round5/reference/src/pack.c.o

.PHONY : Round5/reference/src/pack.o

# target to build an object file
Round5/reference/src/pack.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/pack.c.o
.PHONY : Round5/reference/src/pack.c.o

Round5/reference/src/pack.i: Round5/reference/src/pack.c.i

.PHONY : Round5/reference/src/pack.i

# target to preprocess a source file
Round5/reference/src/pack.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/pack.c.i
.PHONY : Round5/reference/src/pack.c.i

Round5/reference/src/pack.s: Round5/reference/src/pack.c.s

.PHONY : Round5/reference/src/pack.s

# target to generate assembly for a file
Round5/reference/src/pack.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/pack.c.s
.PHONY : Round5/reference/src/pack.c.s

Round5/reference/src/parameters.o: Round5/reference/src/parameters.c.o

.PHONY : Round5/reference/src/parameters.o

# target to build an object file
Round5/reference/src/parameters.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/parameters.c.o
.PHONY : Round5/reference/src/parameters.c.o

Round5/reference/src/parameters.i: Round5/reference/src/parameters.c.i

.PHONY : Round5/reference/src/parameters.i

# target to preprocess a source file
Round5/reference/src/parameters.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/parameters.c.i
.PHONY : Round5/reference/src/parameters.c.i

Round5/reference/src/parameters.s: Round5/reference/src/parameters.c.s

.PHONY : Round5/reference/src/parameters.s

# target to generate assembly for a file
Round5/reference/src/parameters.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/parameters.c.s
.PHONY : Round5/reference/src/parameters.c.s

Round5/reference/src/r5_cca_kem.o: Round5/reference/src/r5_cca_kem.c.o

.PHONY : Round5/reference/src/r5_cca_kem.o

# target to build an object file
Round5/reference/src/r5_cca_kem.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_cca_kem.c.o
.PHONY : Round5/reference/src/r5_cca_kem.c.o

Round5/reference/src/r5_cca_kem.i: Round5/reference/src/r5_cca_kem.c.i

.PHONY : Round5/reference/src/r5_cca_kem.i

# target to preprocess a source file
Round5/reference/src/r5_cca_kem.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_cca_kem.c.i
.PHONY : Round5/reference/src/r5_cca_kem.c.i

Round5/reference/src/r5_cca_kem.s: Round5/reference/src/r5_cca_kem.c.s

.PHONY : Round5/reference/src/r5_cca_kem.s

# target to generate assembly for a file
Round5/reference/src/r5_cca_kem.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_cca_kem.c.s
.PHONY : Round5/reference/src/r5_cca_kem.c.s

Round5/reference/src/r5_cca_pke.o: Round5/reference/src/r5_cca_pke.c.o

.PHONY : Round5/reference/src/r5_cca_pke.o

# target to build an object file
Round5/reference/src/r5_cca_pke.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_cca_pke.c.o
.PHONY : Round5/reference/src/r5_cca_pke.c.o

Round5/reference/src/r5_cca_pke.i: Round5/reference/src/r5_cca_pke.c.i

.PHONY : Round5/reference/src/r5_cca_pke.i

# target to preprocess a source file
Round5/reference/src/r5_cca_pke.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_cca_pke.c.i
.PHONY : Round5/reference/src/r5_cca_pke.c.i

Round5/reference/src/r5_cca_pke.s: Round5/reference/src/r5_cca_pke.c.s

.PHONY : Round5/reference/src/r5_cca_pke.s

# target to generate assembly for a file
Round5/reference/src/r5_cca_pke.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_cca_pke.c.s
.PHONY : Round5/reference/src/r5_cca_pke.c.s

Round5/reference/src/r5_core.o: Round5/reference/src/r5_core.c.o

.PHONY : Round5/reference/src/r5_core.o

# target to build an object file
Round5/reference/src/r5_core.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_core.c.o
.PHONY : Round5/reference/src/r5_core.c.o

Round5/reference/src/r5_core.i: Round5/reference/src/r5_core.c.i

.PHONY : Round5/reference/src/r5_core.i

# target to preprocess a source file
Round5/reference/src/r5_core.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_core.c.i
.PHONY : Round5/reference/src/r5_core.c.i

Round5/reference/src/r5_core.s: Round5/reference/src/r5_core.c.s

.PHONY : Round5/reference/src/r5_core.s

# target to generate assembly for a file
Round5/reference/src/r5_core.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_core.c.s
.PHONY : Round5/reference/src/r5_core.c.s

Round5/reference/src/r5_cpa_kem.o: Round5/reference/src/r5_cpa_kem.c.o

.PHONY : Round5/reference/src/r5_cpa_kem.o

# target to build an object file
Round5/reference/src/r5_cpa_kem.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_cpa_kem.c.o
.PHONY : Round5/reference/src/r5_cpa_kem.c.o

Round5/reference/src/r5_cpa_kem.i: Round5/reference/src/r5_cpa_kem.c.i

.PHONY : Round5/reference/src/r5_cpa_kem.i

# target to preprocess a source file
Round5/reference/src/r5_cpa_kem.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_cpa_kem.c.i
.PHONY : Round5/reference/src/r5_cpa_kem.c.i

Round5/reference/src/r5_cpa_kem.s: Round5/reference/src/r5_cpa_kem.c.s

.PHONY : Round5/reference/src/r5_cpa_kem.s

# target to generate assembly for a file
Round5/reference/src/r5_cpa_kem.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_cpa_kem.c.s
.PHONY : Round5/reference/src/r5_cpa_kem.c.s

Round5/reference/src/r5_cpa_pke.o: Round5/reference/src/r5_cpa_pke.c.o

.PHONY : Round5/reference/src/r5_cpa_pke.o

# target to build an object file
Round5/reference/src/r5_cpa_pke.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_cpa_pke.c.o
.PHONY : Round5/reference/src/r5_cpa_pke.c.o

Round5/reference/src/r5_cpa_pke.i: Round5/reference/src/r5_cpa_pke.c.i

.PHONY : Round5/reference/src/r5_cpa_pke.i

# target to preprocess a source file
Round5/reference/src/r5_cpa_pke.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_cpa_pke.c.i
.PHONY : Round5/reference/src/r5_cpa_pke.c.i

Round5/reference/src/r5_cpa_pke.s: Round5/reference/src/r5_cpa_pke.c.s

.PHONY : Round5/reference/src/r5_cpa_pke.s

# target to generate assembly for a file
Round5/reference/src/r5_cpa_pke.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_cpa_pke.c.s
.PHONY : Round5/reference/src/r5_cpa_pke.c.s

Round5/reference/src/r5_dem.o: Round5/reference/src/r5_dem.c.o

.PHONY : Round5/reference/src/r5_dem.o

# target to build an object file
Round5/reference/src/r5_dem.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_dem.c.o
.PHONY : Round5/reference/src/r5_dem.c.o

Round5/reference/src/r5_dem.i: Round5/reference/src/r5_dem.c.i

.PHONY : Round5/reference/src/r5_dem.i

# target to preprocess a source file
Round5/reference/src/r5_dem.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_dem.c.i
.PHONY : Round5/reference/src/r5_dem.c.i

Round5/reference/src/r5_dem.s: Round5/reference/src/r5_dem.c.s

.PHONY : Round5/reference/src/r5_dem.s

# target to generate assembly for a file
Round5/reference/src/r5_dem.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_dem.c.s
.PHONY : Round5/reference/src/r5_dem.c.s

Round5/reference/src/r5_hash.o: Round5/reference/src/r5_hash.c.o

.PHONY : Round5/reference/src/r5_hash.o

# target to build an object file
Round5/reference/src/r5_hash.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_hash.c.o
.PHONY : Round5/reference/src/r5_hash.c.o

Round5/reference/src/r5_hash.i: Round5/reference/src/r5_hash.c.i

.PHONY : Round5/reference/src/r5_hash.i

# target to preprocess a source file
Round5/reference/src/r5_hash.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_hash.c.i
.PHONY : Round5/reference/src/r5_hash.c.i

Round5/reference/src/r5_hash.s: Round5/reference/src/r5_hash.c.s

.PHONY : Round5/reference/src/r5_hash.s

# target to generate assembly for a file
Round5/reference/src/r5_hash.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_hash.c.s
.PHONY : Round5/reference/src/r5_hash.c.s

Round5/reference/src/r5_memory.o: Round5/reference/src/r5_memory.c.o

.PHONY : Round5/reference/src/r5_memory.o

# target to build an object file
Round5/reference/src/r5_memory.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_memory.c.o
.PHONY : Round5/reference/src/r5_memory.c.o

Round5/reference/src/r5_memory.i: Round5/reference/src/r5_memory.c.i

.PHONY : Round5/reference/src/r5_memory.i

# target to preprocess a source file
Round5/reference/src/r5_memory.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_memory.c.i
.PHONY : Round5/reference/src/r5_memory.c.i

Round5/reference/src/r5_memory.s: Round5/reference/src/r5_memory.c.s

.PHONY : Round5/reference/src/r5_memory.s

# target to generate assembly for a file
Round5/reference/src/r5_memory.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_memory.c.s
.PHONY : Round5/reference/src/r5_memory.c.s

Round5/reference/src/r5_parameter_sets.o: Round5/reference/src/r5_parameter_sets.c.o

.PHONY : Round5/reference/src/r5_parameter_sets.o

# target to build an object file
Round5/reference/src/r5_parameter_sets.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_parameter_sets.c.o
.PHONY : Round5/reference/src/r5_parameter_sets.c.o

Round5/reference/src/r5_parameter_sets.i: Round5/reference/src/r5_parameter_sets.c.i

.PHONY : Round5/reference/src/r5_parameter_sets.i

# target to preprocess a source file
Round5/reference/src/r5_parameter_sets.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_parameter_sets.c.i
.PHONY : Round5/reference/src/r5_parameter_sets.c.i

Round5/reference/src/r5_parameter_sets.s: Round5/reference/src/r5_parameter_sets.c.s

.PHONY : Round5/reference/src/r5_parameter_sets.s

# target to generate assembly for a file
Round5/reference/src/r5_parameter_sets.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/r5_parameter_sets.c.s
.PHONY : Round5/reference/src/r5_parameter_sets.c.s

Round5/reference/src/shake.o: Round5/reference/src/shake.c.o

.PHONY : Round5/reference/src/shake.o

# target to build an object file
Round5/reference/src/shake.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/shake.c.o
.PHONY : Round5/reference/src/shake.c.o

Round5/reference/src/shake.i: Round5/reference/src/shake.c.i

.PHONY : Round5/reference/src/shake.i

# target to preprocess a source file
Round5/reference/src/shake.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/shake.c.i
.PHONY : Round5/reference/src/shake.c.i

Round5/reference/src/shake.s: Round5/reference/src/shake.c.s

.PHONY : Round5/reference/src/shake.s

# target to generate assembly for a file
Round5/reference/src/shake.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/shake.c.s
.PHONY : Round5/reference/src/shake.c.s

Round5/reference/src/xef_ref.o: Round5/reference/src/xef_ref.c.o

.PHONY : Round5/reference/src/xef_ref.o

# target to build an object file
Round5/reference/src/xef_ref.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/xef_ref.c.o
.PHONY : Round5/reference/src/xef_ref.c.o

Round5/reference/src/xef_ref.i: Round5/reference/src/xef_ref.c.i

.PHONY : Round5/reference/src/xef_ref.i

# target to preprocess a source file
Round5/reference/src/xef_ref.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/xef_ref.c.i
.PHONY : Round5/reference/src/xef_ref.c.i

Round5/reference/src/xef_ref.s: Round5/reference/src/xef_ref.c.s

.PHONY : Round5/reference/src/xef_ref.s

# target to generate assembly for a file
Round5/reference/src/xef_ref.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/Round5/reference/src/xef_ref.c.s
.PHONY : Round5/reference/src/xef_ref.c.s

XKCP/lib/high/KangarooTwelve/KangarooTwelve.o: XKCP/lib/high/KangarooTwelve/KangarooTwelve.c.o

.PHONY : XKCP/lib/high/KangarooTwelve/KangarooTwelve.o

# target to build an object file
XKCP/lib/high/KangarooTwelve/KangarooTwelve.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/KangarooTwelve/KangarooTwelve.c.o
.PHONY : XKCP/lib/high/KangarooTwelve/KangarooTwelve.c.o

XKCP/lib/high/KangarooTwelve/KangarooTwelve.i: XKCP/lib/high/KangarooTwelve/KangarooTwelve.c.i

.PHONY : XKCP/lib/high/KangarooTwelve/KangarooTwelve.i

# target to preprocess a source file
XKCP/lib/high/KangarooTwelve/KangarooTwelve.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/KangarooTwelve/KangarooTwelve.c.i
.PHONY : XKCP/lib/high/KangarooTwelve/KangarooTwelve.c.i

XKCP/lib/high/KangarooTwelve/KangarooTwelve.s: XKCP/lib/high/KangarooTwelve/KangarooTwelve.c.s

.PHONY : XKCP/lib/high/KangarooTwelve/KangarooTwelve.s

# target to generate assembly for a file
XKCP/lib/high/KangarooTwelve/KangarooTwelve.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/KangarooTwelve/KangarooTwelve.c.s
.PHONY : XKCP/lib/high/KangarooTwelve/KangarooTwelve.c.s

XKCP/lib/high/Keccak/FIPS202/KeccakHash.o: XKCP/lib/high/Keccak/FIPS202/KeccakHash.c.o

.PHONY : XKCP/lib/high/Keccak/FIPS202/KeccakHash.o

# target to build an object file
XKCP/lib/high/Keccak/FIPS202/KeccakHash.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/FIPS202/KeccakHash.c.o
.PHONY : XKCP/lib/high/Keccak/FIPS202/KeccakHash.c.o

XKCP/lib/high/Keccak/FIPS202/KeccakHash.i: XKCP/lib/high/Keccak/FIPS202/KeccakHash.c.i

.PHONY : XKCP/lib/high/Keccak/FIPS202/KeccakHash.i

# target to preprocess a source file
XKCP/lib/high/Keccak/FIPS202/KeccakHash.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/FIPS202/KeccakHash.c.i
.PHONY : XKCP/lib/high/Keccak/FIPS202/KeccakHash.c.i

XKCP/lib/high/Keccak/FIPS202/KeccakHash.s: XKCP/lib/high/Keccak/FIPS202/KeccakHash.c.s

.PHONY : XKCP/lib/high/Keccak/FIPS202/KeccakHash.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/FIPS202/KeccakHash.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/FIPS202/KeccakHash.c.s
.PHONY : XKCP/lib/high/Keccak/FIPS202/KeccakHash.c.s

XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.o: XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.c.o

.PHONY : XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.o

# target to build an object file
XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.c.o
.PHONY : XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.c.o

XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.i: XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.c.i

.PHONY : XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.i

# target to preprocess a source file
XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.c.i
.PHONY : XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.c.i

XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.s: XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.c.s

.PHONY : XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.c.s
.PHONY : XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.c.s

XKCP/lib/high/Keccak/KeccakDuplexWidth1600.o: XKCP/lib/high/Keccak/KeccakDuplexWidth1600.c.o

.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth1600.o

# target to build an object file
XKCP/lib/high/Keccak/KeccakDuplexWidth1600.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakDuplexWidth1600.c.o
.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth1600.c.o

XKCP/lib/high/Keccak/KeccakDuplexWidth1600.i: XKCP/lib/high/Keccak/KeccakDuplexWidth1600.c.i

.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth1600.i

# target to preprocess a source file
XKCP/lib/high/Keccak/KeccakDuplexWidth1600.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakDuplexWidth1600.c.i
.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth1600.c.i

XKCP/lib/high/Keccak/KeccakDuplexWidth1600.s: XKCP/lib/high/Keccak/KeccakDuplexWidth1600.c.s

.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth1600.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/KeccakDuplexWidth1600.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakDuplexWidth1600.c.s
.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth1600.c.s

XKCP/lib/high/Keccak/KeccakDuplexWidth200.o: XKCP/lib/high/Keccak/KeccakDuplexWidth200.c.o

.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth200.o

# target to build an object file
XKCP/lib/high/Keccak/KeccakDuplexWidth200.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakDuplexWidth200.c.o
.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth200.c.o

XKCP/lib/high/Keccak/KeccakDuplexWidth200.i: XKCP/lib/high/Keccak/KeccakDuplexWidth200.c.i

.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth200.i

# target to preprocess a source file
XKCP/lib/high/Keccak/KeccakDuplexWidth200.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakDuplexWidth200.c.i
.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth200.c.i

XKCP/lib/high/Keccak/KeccakDuplexWidth200.s: XKCP/lib/high/Keccak/KeccakDuplexWidth200.c.s

.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth200.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/KeccakDuplexWidth200.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakDuplexWidth200.c.s
.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth200.c.s

XKCP/lib/high/Keccak/KeccakDuplexWidth400.o: XKCP/lib/high/Keccak/KeccakDuplexWidth400.c.o

.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth400.o

# target to build an object file
XKCP/lib/high/Keccak/KeccakDuplexWidth400.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakDuplexWidth400.c.o
.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth400.c.o

XKCP/lib/high/Keccak/KeccakDuplexWidth400.i: XKCP/lib/high/Keccak/KeccakDuplexWidth400.c.i

.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth400.i

# target to preprocess a source file
XKCP/lib/high/Keccak/KeccakDuplexWidth400.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakDuplexWidth400.c.i
.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth400.c.i

XKCP/lib/high/Keccak/KeccakDuplexWidth400.s: XKCP/lib/high/Keccak/KeccakDuplexWidth400.c.s

.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth400.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/KeccakDuplexWidth400.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakDuplexWidth400.c.s
.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth400.c.s

XKCP/lib/high/Keccak/KeccakDuplexWidth800.o: XKCP/lib/high/Keccak/KeccakDuplexWidth800.c.o

.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth800.o

# target to build an object file
XKCP/lib/high/Keccak/KeccakDuplexWidth800.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakDuplexWidth800.c.o
.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth800.c.o

XKCP/lib/high/Keccak/KeccakDuplexWidth800.i: XKCP/lib/high/Keccak/KeccakDuplexWidth800.c.i

.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth800.i

# target to preprocess a source file
XKCP/lib/high/Keccak/KeccakDuplexWidth800.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakDuplexWidth800.c.i
.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth800.c.i

XKCP/lib/high/Keccak/KeccakDuplexWidth800.s: XKCP/lib/high/Keccak/KeccakDuplexWidth800.c.s

.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth800.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/KeccakDuplexWidth800.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakDuplexWidth800.c.s
.PHONY : XKCP/lib/high/Keccak/KeccakDuplexWidth800.c.s

XKCP/lib/high/Keccak/KeccakSpongeWidth1600.o: XKCP/lib/high/Keccak/KeccakSpongeWidth1600.c.o

.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth1600.o

# target to build an object file
XKCP/lib/high/Keccak/KeccakSpongeWidth1600.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakSpongeWidth1600.c.o
.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth1600.c.o

XKCP/lib/high/Keccak/KeccakSpongeWidth1600.i: XKCP/lib/high/Keccak/KeccakSpongeWidth1600.c.i

.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth1600.i

# target to preprocess a source file
XKCP/lib/high/Keccak/KeccakSpongeWidth1600.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakSpongeWidth1600.c.i
.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth1600.c.i

XKCP/lib/high/Keccak/KeccakSpongeWidth1600.s: XKCP/lib/high/Keccak/KeccakSpongeWidth1600.c.s

.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth1600.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/KeccakSpongeWidth1600.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakSpongeWidth1600.c.s
.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth1600.c.s

XKCP/lib/high/Keccak/KeccakSpongeWidth200.o: XKCP/lib/high/Keccak/KeccakSpongeWidth200.c.o

.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth200.o

# target to build an object file
XKCP/lib/high/Keccak/KeccakSpongeWidth200.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakSpongeWidth200.c.o
.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth200.c.o

XKCP/lib/high/Keccak/KeccakSpongeWidth200.i: XKCP/lib/high/Keccak/KeccakSpongeWidth200.c.i

.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth200.i

# target to preprocess a source file
XKCP/lib/high/Keccak/KeccakSpongeWidth200.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakSpongeWidth200.c.i
.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth200.c.i

XKCP/lib/high/Keccak/KeccakSpongeWidth200.s: XKCP/lib/high/Keccak/KeccakSpongeWidth200.c.s

.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth200.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/KeccakSpongeWidth200.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakSpongeWidth200.c.s
.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth200.c.s

XKCP/lib/high/Keccak/KeccakSpongeWidth400.o: XKCP/lib/high/Keccak/KeccakSpongeWidth400.c.o

.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth400.o

# target to build an object file
XKCP/lib/high/Keccak/KeccakSpongeWidth400.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakSpongeWidth400.c.o
.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth400.c.o

XKCP/lib/high/Keccak/KeccakSpongeWidth400.i: XKCP/lib/high/Keccak/KeccakSpongeWidth400.c.i

.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth400.i

# target to preprocess a source file
XKCP/lib/high/Keccak/KeccakSpongeWidth400.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakSpongeWidth400.c.i
.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth400.c.i

XKCP/lib/high/Keccak/KeccakSpongeWidth400.s: XKCP/lib/high/Keccak/KeccakSpongeWidth400.c.s

.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth400.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/KeccakSpongeWidth400.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakSpongeWidth400.c.s
.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth400.c.s

XKCP/lib/high/Keccak/KeccakSpongeWidth800.o: XKCP/lib/high/Keccak/KeccakSpongeWidth800.c.o

.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth800.o

# target to build an object file
XKCP/lib/high/Keccak/KeccakSpongeWidth800.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakSpongeWidth800.c.o
.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth800.c.o

XKCP/lib/high/Keccak/KeccakSpongeWidth800.i: XKCP/lib/high/Keccak/KeccakSpongeWidth800.c.i

.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth800.i

# target to preprocess a source file
XKCP/lib/high/Keccak/KeccakSpongeWidth800.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakSpongeWidth800.c.i
.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth800.c.i

XKCP/lib/high/Keccak/KeccakSpongeWidth800.s: XKCP/lib/high/Keccak/KeccakSpongeWidth800.c.s

.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth800.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/KeccakSpongeWidth800.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/KeccakSpongeWidth800.c.s
.PHONY : XKCP/lib/high/Keccak/KeccakSpongeWidth800.c.s

XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.o: XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.c.o

.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.o

# target to build an object file
XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.c.o
.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.c.o

XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.i: XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.c.i

.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.i

# target to preprocess a source file
XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.c.i
.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.c.i

XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.s: XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.c.s

.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.c.s
.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.c.s

XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.o: XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.c.o

.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.o

# target to build an object file
XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.c.o
.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.c.o

XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.i: XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.c.i

.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.i

# target to preprocess a source file
XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.c.i
.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.c.i

XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.s: XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.c.s

.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.c.s
.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.c.s

XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.o: XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.c.o

.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.o

# target to build an object file
XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.c.o
.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.c.o

XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.i: XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.c.i

.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.i

# target to preprocess a source file
XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.c.i
.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.c.i

XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.s: XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.c.s

.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.c.s
.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.c.s

XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.o: XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.c.o

.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.o

# target to build an object file
XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.c.o
.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.c.o

XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.i: XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.c.i

.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.i

# target to preprocess a source file
XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.c.i
.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.c.i

XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.s: XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.c.s

.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.c.s
.PHONY : XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.c.s

XKCP/lib/high/Keccak/SP800-185/SP800-185.o: XKCP/lib/high/Keccak/SP800-185/SP800-185.c.o

.PHONY : XKCP/lib/high/Keccak/SP800-185/SP800-185.o

# target to build an object file
XKCP/lib/high/Keccak/SP800-185/SP800-185.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/SP800-185/SP800-185.c.o
.PHONY : XKCP/lib/high/Keccak/SP800-185/SP800-185.c.o

XKCP/lib/high/Keccak/SP800-185/SP800-185.i: XKCP/lib/high/Keccak/SP800-185/SP800-185.c.i

.PHONY : XKCP/lib/high/Keccak/SP800-185/SP800-185.i

# target to preprocess a source file
XKCP/lib/high/Keccak/SP800-185/SP800-185.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/SP800-185/SP800-185.c.i
.PHONY : XKCP/lib/high/Keccak/SP800-185/SP800-185.c.i

XKCP/lib/high/Keccak/SP800-185/SP800-185.s: XKCP/lib/high/Keccak/SP800-185/SP800-185.c.s

.PHONY : XKCP/lib/high/Keccak/SP800-185/SP800-185.s

# target to generate assembly for a file
XKCP/lib/high/Keccak/SP800-185/SP800-185.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keccak/SP800-185/SP800-185.c.s
.PHONY : XKCP/lib/high/Keccak/SP800-185/SP800-185.c.s

XKCP/lib/high/Ketje/KetjeJr.o: XKCP/lib/high/Ketje/KetjeJr.c.o

.PHONY : XKCP/lib/high/Ketje/KetjeJr.o

# target to build an object file
XKCP/lib/high/Ketje/KetjeJr.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Ketje/KetjeJr.c.o
.PHONY : XKCP/lib/high/Ketje/KetjeJr.c.o

XKCP/lib/high/Ketje/KetjeJr.i: XKCP/lib/high/Ketje/KetjeJr.c.i

.PHONY : XKCP/lib/high/Ketje/KetjeJr.i

# target to preprocess a source file
XKCP/lib/high/Ketje/KetjeJr.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Ketje/KetjeJr.c.i
.PHONY : XKCP/lib/high/Ketje/KetjeJr.c.i

XKCP/lib/high/Ketje/KetjeJr.s: XKCP/lib/high/Ketje/KetjeJr.c.s

.PHONY : XKCP/lib/high/Ketje/KetjeJr.s

# target to generate assembly for a file
XKCP/lib/high/Ketje/KetjeJr.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Ketje/KetjeJr.c.s
.PHONY : XKCP/lib/high/Ketje/KetjeJr.c.s

XKCP/lib/high/Ketje/KetjeMj.o: XKCP/lib/high/Ketje/KetjeMj.c.o

.PHONY : XKCP/lib/high/Ketje/KetjeMj.o

# target to build an object file
XKCP/lib/high/Ketje/KetjeMj.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Ketje/KetjeMj.c.o
.PHONY : XKCP/lib/high/Ketje/KetjeMj.c.o

XKCP/lib/high/Ketje/KetjeMj.i: XKCP/lib/high/Ketje/KetjeMj.c.i

.PHONY : XKCP/lib/high/Ketje/KetjeMj.i

# target to preprocess a source file
XKCP/lib/high/Ketje/KetjeMj.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Ketje/KetjeMj.c.i
.PHONY : XKCP/lib/high/Ketje/KetjeMj.c.i

XKCP/lib/high/Ketje/KetjeMj.s: XKCP/lib/high/Ketje/KetjeMj.c.s

.PHONY : XKCP/lib/high/Ketje/KetjeMj.s

# target to generate assembly for a file
XKCP/lib/high/Ketje/KetjeMj.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Ketje/KetjeMj.c.s
.PHONY : XKCP/lib/high/Ketje/KetjeMj.c.s

XKCP/lib/high/Ketje/KetjeMn.o: XKCP/lib/high/Ketje/KetjeMn.c.o

.PHONY : XKCP/lib/high/Ketje/KetjeMn.o

# target to build an object file
XKCP/lib/high/Ketje/KetjeMn.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Ketje/KetjeMn.c.o
.PHONY : XKCP/lib/high/Ketje/KetjeMn.c.o

XKCP/lib/high/Ketje/KetjeMn.i: XKCP/lib/high/Ketje/KetjeMn.c.i

.PHONY : XKCP/lib/high/Ketje/KetjeMn.i

# target to preprocess a source file
XKCP/lib/high/Ketje/KetjeMn.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Ketje/KetjeMn.c.i
.PHONY : XKCP/lib/high/Ketje/KetjeMn.c.i

XKCP/lib/high/Ketje/KetjeMn.s: XKCP/lib/high/Ketje/KetjeMn.c.s

.PHONY : XKCP/lib/high/Ketje/KetjeMn.s

# target to generate assembly for a file
XKCP/lib/high/Ketje/KetjeMn.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Ketje/KetjeMn.c.s
.PHONY : XKCP/lib/high/Ketje/KetjeMn.c.s

XKCP/lib/high/Ketje/KetjeSr.o: XKCP/lib/high/Ketje/KetjeSr.c.o

.PHONY : XKCP/lib/high/Ketje/KetjeSr.o

# target to build an object file
XKCP/lib/high/Ketje/KetjeSr.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Ketje/KetjeSr.c.o
.PHONY : XKCP/lib/high/Ketje/KetjeSr.c.o

XKCP/lib/high/Ketje/KetjeSr.i: XKCP/lib/high/Ketje/KetjeSr.c.i

.PHONY : XKCP/lib/high/Ketje/KetjeSr.i

# target to preprocess a source file
XKCP/lib/high/Ketje/KetjeSr.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Ketje/KetjeSr.c.i
.PHONY : XKCP/lib/high/Ketje/KetjeSr.c.i

XKCP/lib/high/Ketje/KetjeSr.s: XKCP/lib/high/Ketje/KetjeSr.c.s

.PHONY : XKCP/lib/high/Ketje/KetjeSr.s

# target to generate assembly for a file
XKCP/lib/high/Ketje/KetjeSr.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Ketje/KetjeSr.c.s
.PHONY : XKCP/lib/high/Ketje/KetjeSr.c.s

XKCP/lib/high/Keyak/LakeKeyak.o: XKCP/lib/high/Keyak/LakeKeyak.c.o

.PHONY : XKCP/lib/high/Keyak/LakeKeyak.o

# target to build an object file
XKCP/lib/high/Keyak/LakeKeyak.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/LakeKeyak.c.o
.PHONY : XKCP/lib/high/Keyak/LakeKeyak.c.o

XKCP/lib/high/Keyak/LakeKeyak.i: XKCP/lib/high/Keyak/LakeKeyak.c.i

.PHONY : XKCP/lib/high/Keyak/LakeKeyak.i

# target to preprocess a source file
XKCP/lib/high/Keyak/LakeKeyak.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/LakeKeyak.c.i
.PHONY : XKCP/lib/high/Keyak/LakeKeyak.c.i

XKCP/lib/high/Keyak/LakeKeyak.s: XKCP/lib/high/Keyak/LakeKeyak.c.s

.PHONY : XKCP/lib/high/Keyak/LakeKeyak.s

# target to generate assembly for a file
XKCP/lib/high/Keyak/LakeKeyak.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/LakeKeyak.c.s
.PHONY : XKCP/lib/high/Keyak/LakeKeyak.c.s

XKCP/lib/high/Keyak/LunarKeyak.o: XKCP/lib/high/Keyak/LunarKeyak.c.o

.PHONY : XKCP/lib/high/Keyak/LunarKeyak.o

# target to build an object file
XKCP/lib/high/Keyak/LunarKeyak.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/LunarKeyak.c.o
.PHONY : XKCP/lib/high/Keyak/LunarKeyak.c.o

XKCP/lib/high/Keyak/LunarKeyak.i: XKCP/lib/high/Keyak/LunarKeyak.c.i

.PHONY : XKCP/lib/high/Keyak/LunarKeyak.i

# target to preprocess a source file
XKCP/lib/high/Keyak/LunarKeyak.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/LunarKeyak.c.i
.PHONY : XKCP/lib/high/Keyak/LunarKeyak.c.i

XKCP/lib/high/Keyak/LunarKeyak.s: XKCP/lib/high/Keyak/LunarKeyak.c.s

.PHONY : XKCP/lib/high/Keyak/LunarKeyak.s

# target to generate assembly for a file
XKCP/lib/high/Keyak/LunarKeyak.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/LunarKeyak.c.s
.PHONY : XKCP/lib/high/Keyak/LunarKeyak.c.s

XKCP/lib/high/Keyak/OceanKeyak.o: XKCP/lib/high/Keyak/OceanKeyak.c.o

.PHONY : XKCP/lib/high/Keyak/OceanKeyak.o

# target to build an object file
XKCP/lib/high/Keyak/OceanKeyak.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/OceanKeyak.c.o
.PHONY : XKCP/lib/high/Keyak/OceanKeyak.c.o

XKCP/lib/high/Keyak/OceanKeyak.i: XKCP/lib/high/Keyak/OceanKeyak.c.i

.PHONY : XKCP/lib/high/Keyak/OceanKeyak.i

# target to preprocess a source file
XKCP/lib/high/Keyak/OceanKeyak.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/OceanKeyak.c.i
.PHONY : XKCP/lib/high/Keyak/OceanKeyak.c.i

XKCP/lib/high/Keyak/OceanKeyak.s: XKCP/lib/high/Keyak/OceanKeyak.c.s

.PHONY : XKCP/lib/high/Keyak/OceanKeyak.s

# target to generate assembly for a file
XKCP/lib/high/Keyak/OceanKeyak.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/OceanKeyak.c.s
.PHONY : XKCP/lib/high/Keyak/OceanKeyak.c.s

XKCP/lib/high/Keyak/RiverKeyak.o: XKCP/lib/high/Keyak/RiverKeyak.c.o

.PHONY : XKCP/lib/high/Keyak/RiverKeyak.o

# target to build an object file
XKCP/lib/high/Keyak/RiverKeyak.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/RiverKeyak.c.o
.PHONY : XKCP/lib/high/Keyak/RiverKeyak.c.o

XKCP/lib/high/Keyak/RiverKeyak.i: XKCP/lib/high/Keyak/RiverKeyak.c.i

.PHONY : XKCP/lib/high/Keyak/RiverKeyak.i

# target to preprocess a source file
XKCP/lib/high/Keyak/RiverKeyak.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/RiverKeyak.c.i
.PHONY : XKCP/lib/high/Keyak/RiverKeyak.c.i

XKCP/lib/high/Keyak/RiverKeyak.s: XKCP/lib/high/Keyak/RiverKeyak.c.s

.PHONY : XKCP/lib/high/Keyak/RiverKeyak.s

# target to generate assembly for a file
XKCP/lib/high/Keyak/RiverKeyak.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/RiverKeyak.c.s
.PHONY : XKCP/lib/high/Keyak/RiverKeyak.c.s

XKCP/lib/high/Keyak/SeaKeyak.o: XKCP/lib/high/Keyak/SeaKeyak.c.o

.PHONY : XKCP/lib/high/Keyak/SeaKeyak.o

# target to build an object file
XKCP/lib/high/Keyak/SeaKeyak.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/SeaKeyak.c.o
.PHONY : XKCP/lib/high/Keyak/SeaKeyak.c.o

XKCP/lib/high/Keyak/SeaKeyak.i: XKCP/lib/high/Keyak/SeaKeyak.c.i

.PHONY : XKCP/lib/high/Keyak/SeaKeyak.i

# target to preprocess a source file
XKCP/lib/high/Keyak/SeaKeyak.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/SeaKeyak.c.i
.PHONY : XKCP/lib/high/Keyak/SeaKeyak.c.i

XKCP/lib/high/Keyak/SeaKeyak.s: XKCP/lib/high/Keyak/SeaKeyak.c.s

.PHONY : XKCP/lib/high/Keyak/SeaKeyak.s

# target to generate assembly for a file
XKCP/lib/high/Keyak/SeaKeyak.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/high/Keyak/SeaKeyak.c.s
.PHONY : XKCP/lib/high/Keyak/SeaKeyak.c.s

XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.o: XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.c.o

.PHONY : XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.o

# target to build an object file
XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.c.o
.PHONY : XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.c.o

XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.i: XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.c.i

.PHONY : XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.i

# target to preprocess a source file
XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.c.i
.PHONY : XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.c.i

XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.s: XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.c.s

.PHONY : XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.s

# target to generate assembly for a file
XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.c.s
.PHONY : XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.c.s

XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.o: XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.c.o

.PHONY : XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.o

# target to build an object file
XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.c.o
.PHONY : XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.c.o

XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.i: XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.c.i

.PHONY : XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.i

# target to preprocess a source file
XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.c.i
.PHONY : XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.c.i

XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.s: XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.c.s

.PHONY : XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.s

# target to generate assembly for a file
XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.c.s
.PHONY : XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.c.s

XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.o: XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.c.o

.PHONY : XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.o

# target to build an object file
XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.c.o
.PHONY : XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.c.o

XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.i: XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.c.i

.PHONY : XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.i

# target to preprocess a source file
XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.c.i
.PHONY : XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.c.i

XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.s: XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.c.s

.PHONY : XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.s

# target to generate assembly for a file
XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.c.s
.PHONY : XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.c.s

XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.o: XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c.o

.PHONY : XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.o

# target to build an object file
XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c.o
.PHONY : XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c.o

XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.i: XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c.i

.PHONY : XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.i

# target to preprocess a source file
XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c.i
.PHONY : XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c.i

XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.s: XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c.s

.PHONY : XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.s

# target to generate assembly for a file
XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c.s
.PHONY : XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.c.s

XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.o: XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.c.o

.PHONY : XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.o

# target to build an object file
XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.c.o
.PHONY : XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.c.o

XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.i: XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.c.i

.PHONY : XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.i

# target to preprocess a source file
XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.c.i
.PHONY : XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.c.i

XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.s: XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.c.s

.PHONY : XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.s

# target to generate assembly for a file
XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.c.s
.PHONY : XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.c.s

XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.o: XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.c.o

.PHONY : XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.o

# target to build an object file
XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.c.o
.PHONY : XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.c.o

XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.i: XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.c.i

.PHONY : XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.i

# target to preprocess a source file
XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.c.i
.PHONY : XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.c.i

XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.s: XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.c.s

.PHONY : XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.s

# target to generate assembly for a file
XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.c.s
.PHONY : XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.c.s

XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.o: XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.c.o

.PHONY : XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.o

# target to build an object file
XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.c.o
.PHONY : XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.c.o

XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.i: XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.c.i

.PHONY : XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.i

# target to preprocess a source file
XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.c.i
.PHONY : XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.c.i

XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.s: XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.c.s

.PHONY : XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.s

# target to generate assembly for a file
XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.c.s
.PHONY : XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.c.s

XKCP/lib/low/Ketje/SnP-compliant/KetJr.o: XKCP/lib/low/Ketje/SnP-compliant/KetJr.c.o

.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetJr.o

# target to build an object file
XKCP/lib/low/Ketje/SnP-compliant/KetJr.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/Ketje/SnP-compliant/KetJr.c.o
.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetJr.c.o

XKCP/lib/low/Ketje/SnP-compliant/KetJr.i: XKCP/lib/low/Ketje/SnP-compliant/KetJr.c.i

.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetJr.i

# target to preprocess a source file
XKCP/lib/low/Ketje/SnP-compliant/KetJr.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/Ketje/SnP-compliant/KetJr.c.i
.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetJr.c.i

XKCP/lib/low/Ketje/SnP-compliant/KetJr.s: XKCP/lib/low/Ketje/SnP-compliant/KetJr.c.s

.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetJr.s

# target to generate assembly for a file
XKCP/lib/low/Ketje/SnP-compliant/KetJr.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/Ketje/SnP-compliant/KetJr.c.s
.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetJr.c.s

XKCP/lib/low/Ketje/SnP-compliant/KetMj.o: XKCP/lib/low/Ketje/SnP-compliant/KetMj.c.o

.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetMj.o

# target to build an object file
XKCP/lib/low/Ketje/SnP-compliant/KetMj.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/Ketje/SnP-compliant/KetMj.c.o
.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetMj.c.o

XKCP/lib/low/Ketje/SnP-compliant/KetMj.i: XKCP/lib/low/Ketje/SnP-compliant/KetMj.c.i

.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetMj.i

# target to preprocess a source file
XKCP/lib/low/Ketje/SnP-compliant/KetMj.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/Ketje/SnP-compliant/KetMj.c.i
.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetMj.c.i

XKCP/lib/low/Ketje/SnP-compliant/KetMj.s: XKCP/lib/low/Ketje/SnP-compliant/KetMj.c.s

.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetMj.s

# target to generate assembly for a file
XKCP/lib/low/Ketje/SnP-compliant/KetMj.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/Ketje/SnP-compliant/KetMj.c.s
.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetMj.c.s

XKCP/lib/low/Ketje/SnP-compliant/KetMn.o: XKCP/lib/low/Ketje/SnP-compliant/KetMn.c.o

.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetMn.o

# target to build an object file
XKCP/lib/low/Ketje/SnP-compliant/KetMn.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/Ketje/SnP-compliant/KetMn.c.o
.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetMn.c.o

XKCP/lib/low/Ketje/SnP-compliant/KetMn.i: XKCP/lib/low/Ketje/SnP-compliant/KetMn.c.i

.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetMn.i

# target to preprocess a source file
XKCP/lib/low/Ketje/SnP-compliant/KetMn.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/Ketje/SnP-compliant/KetMn.c.i
.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetMn.c.i

XKCP/lib/low/Ketje/SnP-compliant/KetMn.s: XKCP/lib/low/Ketje/SnP-compliant/KetMn.c.s

.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetMn.s

# target to generate assembly for a file
XKCP/lib/low/Ketje/SnP-compliant/KetMn.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/Ketje/SnP-compliant/KetMn.c.s
.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetMn.c.s

XKCP/lib/low/Ketje/SnP-compliant/KetSr.o: XKCP/lib/low/Ketje/SnP-compliant/KetSr.c.o

.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetSr.o

# target to build an object file
XKCP/lib/low/Ketje/SnP-compliant/KetSr.c.o:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/Ketje/SnP-compliant/KetSr.c.o
.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetSr.c.o

XKCP/lib/low/Ketje/SnP-compliant/KetSr.i: XKCP/lib/low/Ketje/SnP-compliant/KetSr.c.i

.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetSr.i

# target to preprocess a source file
XKCP/lib/low/Ketje/SnP-compliant/KetSr.c.i:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/Ketje/SnP-compliant/KetSr.c.i
.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetSr.c.i

XKCP/lib/low/Ketje/SnP-compliant/KetSr.s: XKCP/lib/low/Ketje/SnP-compliant/KetSr.c.s

.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetSr.s

# target to generate assembly for a file
XKCP/lib/low/Ketje/SnP-compliant/KetSr.c.s:
	$(MAKE) -f CMakeFiles/round5.dir/build.make CMakeFiles/round5.dir/XKCP/lib/low/Ketje/SnP-compliant/KetSr.c.s
.PHONY : XKCP/lib/low/Ketje/SnP-compliant/KetSr.c.s

dilithium/ref/PQCgenKAT_sign.o: dilithium/ref/PQCgenKAT_sign.c.o

.PHONY : dilithium/ref/PQCgenKAT_sign.o

# target to build an object file
dilithium/ref/PQCgenKAT_sign.c.o:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/PQCgenKAT_sign.c.o
.PHONY : dilithium/ref/PQCgenKAT_sign.c.o

dilithium/ref/PQCgenKAT_sign.i: dilithium/ref/PQCgenKAT_sign.c.i

.PHONY : dilithium/ref/PQCgenKAT_sign.i

# target to preprocess a source file
dilithium/ref/PQCgenKAT_sign.c.i:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/PQCgenKAT_sign.c.i
.PHONY : dilithium/ref/PQCgenKAT_sign.c.i

dilithium/ref/PQCgenKAT_sign.s: dilithium/ref/PQCgenKAT_sign.c.s

.PHONY : dilithium/ref/PQCgenKAT_sign.s

# target to generate assembly for a file
dilithium/ref/PQCgenKAT_sign.c.s:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/PQCgenKAT_sign.c.s
.PHONY : dilithium/ref/PQCgenKAT_sign.c.s

dilithium/ref/aes256ctr.o: dilithium/ref/aes256ctr.c.o

.PHONY : dilithium/ref/aes256ctr.o

# target to build an object file
dilithium/ref/aes256ctr.c.o:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/aes256ctr.c.o
.PHONY : dilithium/ref/aes256ctr.c.o

dilithium/ref/aes256ctr.i: dilithium/ref/aes256ctr.c.i

.PHONY : dilithium/ref/aes256ctr.i

# target to preprocess a source file
dilithium/ref/aes256ctr.c.i:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/aes256ctr.c.i
.PHONY : dilithium/ref/aes256ctr.c.i

dilithium/ref/aes256ctr.s: dilithium/ref/aes256ctr.c.s

.PHONY : dilithium/ref/aes256ctr.s

# target to generate assembly for a file
dilithium/ref/aes256ctr.c.s:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/aes256ctr.c.s
.PHONY : dilithium/ref/aes256ctr.c.s

dilithium/ref/fips202.o: dilithium/ref/fips202.c.o

.PHONY : dilithium/ref/fips202.o

# target to build an object file
dilithium/ref/fips202.c.o:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/fips202.c.o
.PHONY : dilithium/ref/fips202.c.o

dilithium/ref/fips202.i: dilithium/ref/fips202.c.i

.PHONY : dilithium/ref/fips202.i

# target to preprocess a source file
dilithium/ref/fips202.c.i:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/fips202.c.i
.PHONY : dilithium/ref/fips202.c.i

dilithium/ref/fips202.s: dilithium/ref/fips202.c.s

.PHONY : dilithium/ref/fips202.s

# target to generate assembly for a file
dilithium/ref/fips202.c.s:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/fips202.c.s
.PHONY : dilithium/ref/fips202.c.s

dilithium/ref/ntt.o: dilithium/ref/ntt.c.o

.PHONY : dilithium/ref/ntt.o

# target to build an object file
dilithium/ref/ntt.c.o:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/ntt.c.o
.PHONY : dilithium/ref/ntt.c.o

dilithium/ref/ntt.i: dilithium/ref/ntt.c.i

.PHONY : dilithium/ref/ntt.i

# target to preprocess a source file
dilithium/ref/ntt.c.i:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/ntt.c.i
.PHONY : dilithium/ref/ntt.c.i

dilithium/ref/ntt.s: dilithium/ref/ntt.c.s

.PHONY : dilithium/ref/ntt.s

# target to generate assembly for a file
dilithium/ref/ntt.c.s:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/ntt.c.s
.PHONY : dilithium/ref/ntt.c.s

dilithium/ref/packing.o: dilithium/ref/packing.c.o

.PHONY : dilithium/ref/packing.o

# target to build an object file
dilithium/ref/packing.c.o:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/packing.c.o
.PHONY : dilithium/ref/packing.c.o

dilithium/ref/packing.i: dilithium/ref/packing.c.i

.PHONY : dilithium/ref/packing.i

# target to preprocess a source file
dilithium/ref/packing.c.i:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/packing.c.i
.PHONY : dilithium/ref/packing.c.i

dilithium/ref/packing.s: dilithium/ref/packing.c.s

.PHONY : dilithium/ref/packing.s

# target to generate assembly for a file
dilithium/ref/packing.c.s:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/packing.c.s
.PHONY : dilithium/ref/packing.c.s

dilithium/ref/poly.o: dilithium/ref/poly.c.o

.PHONY : dilithium/ref/poly.o

# target to build an object file
dilithium/ref/poly.c.o:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/poly.c.o
.PHONY : dilithium/ref/poly.c.o

dilithium/ref/poly.i: dilithium/ref/poly.c.i

.PHONY : dilithium/ref/poly.i

# target to preprocess a source file
dilithium/ref/poly.c.i:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/poly.c.i
.PHONY : dilithium/ref/poly.c.i

dilithium/ref/poly.s: dilithium/ref/poly.c.s

.PHONY : dilithium/ref/poly.s

# target to generate assembly for a file
dilithium/ref/poly.c.s:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/poly.c.s
.PHONY : dilithium/ref/poly.c.s

dilithium/ref/polyvec.o: dilithium/ref/polyvec.c.o

.PHONY : dilithium/ref/polyvec.o

# target to build an object file
dilithium/ref/polyvec.c.o:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/polyvec.c.o
.PHONY : dilithium/ref/polyvec.c.o

dilithium/ref/polyvec.i: dilithium/ref/polyvec.c.i

.PHONY : dilithium/ref/polyvec.i

# target to preprocess a source file
dilithium/ref/polyvec.c.i:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/polyvec.c.i
.PHONY : dilithium/ref/polyvec.c.i

dilithium/ref/polyvec.s: dilithium/ref/polyvec.c.s

.PHONY : dilithium/ref/polyvec.s

# target to generate assembly for a file
dilithium/ref/polyvec.c.s:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/polyvec.c.s
.PHONY : dilithium/ref/polyvec.c.s

dilithium/ref/reduce.o: dilithium/ref/reduce.c.o

.PHONY : dilithium/ref/reduce.o

# target to build an object file
dilithium/ref/reduce.c.o:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/reduce.c.o
.PHONY : dilithium/ref/reduce.c.o

dilithium/ref/reduce.i: dilithium/ref/reduce.c.i

.PHONY : dilithium/ref/reduce.i

# target to preprocess a source file
dilithium/ref/reduce.c.i:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/reduce.c.i
.PHONY : dilithium/ref/reduce.c.i

dilithium/ref/reduce.s: dilithium/ref/reduce.c.s

.PHONY : dilithium/ref/reduce.s

# target to generate assembly for a file
dilithium/ref/reduce.c.s:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/reduce.c.s
.PHONY : dilithium/ref/reduce.c.s

dilithium/ref/rounding.o: dilithium/ref/rounding.c.o

.PHONY : dilithium/ref/rounding.o

# target to build an object file
dilithium/ref/rounding.c.o:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/rounding.c.o
.PHONY : dilithium/ref/rounding.c.o

dilithium/ref/rounding.i: dilithium/ref/rounding.c.i

.PHONY : dilithium/ref/rounding.i

# target to preprocess a source file
dilithium/ref/rounding.c.i:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/rounding.c.i
.PHONY : dilithium/ref/rounding.c.i

dilithium/ref/rounding.s: dilithium/ref/rounding.c.s

.PHONY : dilithium/ref/rounding.s

# target to generate assembly for a file
dilithium/ref/rounding.c.s:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/rounding.c.s
.PHONY : dilithium/ref/rounding.c.s

dilithium/ref/sign.o: dilithium/ref/sign.c.o

.PHONY : dilithium/ref/sign.o

# target to build an object file
dilithium/ref/sign.c.o:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/sign.c.o
.PHONY : dilithium/ref/sign.c.o

dilithium/ref/sign.i: dilithium/ref/sign.c.i

.PHONY : dilithium/ref/sign.i

# target to preprocess a source file
dilithium/ref/sign.c.i:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/sign.c.i
.PHONY : dilithium/ref/sign.c.i

dilithium/ref/sign.s: dilithium/ref/sign.c.s

.PHONY : dilithium/ref/sign.s

# target to generate assembly for a file
dilithium/ref/sign.c.s:
	$(MAKE) -f CMakeFiles/dilithium.dir/build.make CMakeFiles/dilithium.dir/dilithium/ref/sign.c.s
.PHONY : dilithium/ref/sign.c.s

keypair.o: keypair.c.o

.PHONY : keypair.o

# target to build an object file
keypair.c.o:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/keypair.c.o
.PHONY : keypair.c.o

keypair.i: keypair.c.i

.PHONY : keypair.i

# target to preprocess a source file
keypair.c.i:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/keypair.c.i
.PHONY : keypair.c.i

keypair.s: keypair.c.s

.PHONY : keypair.s

# target to generate assembly for a file
keypair.c.s:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/keypair.c.s
.PHONY : keypair.c.s

meths/asn1_meth.o: meths/asn1_meth.c.o

.PHONY : meths/asn1_meth.o

# target to build an object file
meths/asn1_meth.c.o:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/meths/asn1_meth.c.o
.PHONY : meths/asn1_meth.c.o

meths/asn1_meth.i: meths/asn1_meth.c.i

.PHONY : meths/asn1_meth.i

# target to preprocess a source file
meths/asn1_meth.c.i:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/meths/asn1_meth.c.i
.PHONY : meths/asn1_meth.c.i

meths/asn1_meth.s: meths/asn1_meth.c.s

.PHONY : meths/asn1_meth.s

# target to generate assembly for a file
meths/asn1_meth.c.s:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/meths/asn1_meth.c.s
.PHONY : meths/asn1_meth.c.s

meths/round5_meth.o: meths/round5_meth.c.o

.PHONY : meths/round5_meth.o

# target to build an object file
meths/round5_meth.c.o:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/meths/round5_meth.c.o
.PHONY : meths/round5_meth.c.o

meths/round5_meth.i: meths/round5_meth.c.i

.PHONY : meths/round5_meth.i

# target to preprocess a source file
meths/round5_meth.c.i:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/meths/round5_meth.c.i
.PHONY : meths/round5_meth.c.i

meths/round5_meth.s: meths/round5_meth.c.s

.PHONY : meths/round5_meth.s

# target to generate assembly for a file
meths/round5_meth.c.s:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/meths/round5_meth.c.s
.PHONY : meths/round5_meth.c.s

ossl/objects.o: ossl/objects.c.o

.PHONY : ossl/objects.o

# target to build an object file
ossl/objects.c.o:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/ossl/objects.c.o
.PHONY : ossl/objects.c.o

ossl/objects.i: ossl/objects.c.i

.PHONY : ossl/objects.i

# target to preprocess a source file
ossl/objects.c.i:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/ossl/objects.c.i
.PHONY : ossl/objects.c.i

ossl/objects.s: ossl/objects.c.s

.PHONY : ossl/objects.s

# target to generate assembly for a file
ossl/objects.c.s:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/ossl/objects.c.s
.PHONY : ossl/objects.c.s

ossl/ossl_compat.o: ossl/ossl_compat.c.o

.PHONY : ossl/ossl_compat.o

# target to build an object file
ossl/ossl_compat.c.o:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/ossl/ossl_compat.c.o
.PHONY : ossl/ossl_compat.c.o

ossl/ossl_compat.i: ossl/ossl_compat.c.i

.PHONY : ossl/ossl_compat.i

# target to preprocess a source file
ossl/ossl_compat.c.i:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/ossl/ossl_compat.c.i
.PHONY : ossl/ossl_compat.c.i

ossl/ossl_compat.s: ossl/ossl_compat.c.s

.PHONY : ossl/ossl_compat.s

# target to generate assembly for a file
ossl/ossl_compat.c.s:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/ossl/ossl_compat.c.s
.PHONY : ossl/ossl_compat.c.s

round5_engine.o: round5_engine.c.o

.PHONY : round5_engine.o

# target to build an object file
round5_engine.c.o:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/round5_engine.c.o
.PHONY : round5_engine.c.o

round5_engine.i: round5_engine.c.i

.PHONY : round5_engine.i

# target to preprocess a source file
round5_engine.c.i:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/round5_engine.c.i
.PHONY : round5_engine.c.i

round5_engine.s: round5_engine.c.s

.PHONY : round5_engine.s

# target to generate assembly for a file
round5_engine.c.s:
	$(MAKE) -f CMakeFiles/round5_engine.dir/build.make CMakeFiles/round5_engine.dir/round5_engine.c.s
.PHONY : round5_engine.c.s

test/engine_check.o: test/engine_check.c.o

.PHONY : test/engine_check.o

# target to build an object file
test/engine_check.c.o:
	$(MAKE) -f CMakeFiles/engine_check.dir/build.make CMakeFiles/engine_check.dir/test/engine_check.c.o
.PHONY : test/engine_check.c.o

test/engine_check.i: test/engine_check.c.i

.PHONY : test/engine_check.i

# target to preprocess a source file
test/engine_check.c.i:
	$(MAKE) -f CMakeFiles/engine_check.dir/build.make CMakeFiles/engine_check.dir/test/engine_check.c.i
.PHONY : test/engine_check.c.i

test/engine_check.s: test/engine_check.c.s

.PHONY : test/engine_check.s

# target to generate assembly for a file
test/engine_check.c.s:
	$(MAKE) -f CMakeFiles/engine_check.dir/build.make CMakeFiles/engine_check.dir/test/engine_check.c.s
.PHONY : test/engine_check.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... round5"
	@echo "... dilithium"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... engine_check"
	@echo "... round5_engine"
	@echo "... rebuild_cache"
	@echo "... Round5/reference/src/a_fixed.o"
	@echo "... Round5/reference/src/a_fixed.i"
	@echo "... Round5/reference/src/a_fixed.s"
	@echo "... Round5/reference/src/a_random.o"
	@echo "... Round5/reference/src/a_random.i"
	@echo "... Round5/reference/src/a_random.s"
	@echo "... Round5/reference/src/cca_encrypt.o"
	@echo "... Round5/reference/src/cca_encrypt.i"
	@echo "... Round5/reference/src/cca_encrypt.s"
	@echo "... Round5/reference/src/cpa_kem.o"
	@echo "... Round5/reference/src/cpa_kem.i"
	@echo "... Round5/reference/src/cpa_kem.s"
	@echo "... Round5/reference/src/drbg.o"
	@echo "... Round5/reference/src/drbg.i"
	@echo "... Round5/reference/src/drbg.s"
	@echo "... Round5/reference/src/little_endian.o"
	@echo "... Round5/reference/src/little_endian.i"
	@echo "... Round5/reference/src/little_endian.s"
	@echo "... Round5/reference/src/misc.o"
	@echo "... Round5/reference/src/misc.i"
	@echo "... Round5/reference/src/misc.s"
	@echo "... Round5/reference/src/nist_rng.o"
	@echo "... Round5/reference/src/nist_rng.i"
	@echo "... Round5/reference/src/nist_rng.s"
	@echo "... Round5/reference/src/pack.o"
	@echo "... Round5/reference/src/pack.i"
	@echo "... Round5/reference/src/pack.s"
	@echo "... Round5/reference/src/parameters.o"
	@echo "... Round5/reference/src/parameters.i"
	@echo "... Round5/reference/src/parameters.s"
	@echo "... Round5/reference/src/r5_cca_kem.o"
	@echo "... Round5/reference/src/r5_cca_kem.i"
	@echo "... Round5/reference/src/r5_cca_kem.s"
	@echo "... Round5/reference/src/r5_cca_pke.o"
	@echo "... Round5/reference/src/r5_cca_pke.i"
	@echo "... Round5/reference/src/r5_cca_pke.s"
	@echo "... Round5/reference/src/r5_core.o"
	@echo "... Round5/reference/src/r5_core.i"
	@echo "... Round5/reference/src/r5_core.s"
	@echo "... Round5/reference/src/r5_cpa_kem.o"
	@echo "... Round5/reference/src/r5_cpa_kem.i"
	@echo "... Round5/reference/src/r5_cpa_kem.s"
	@echo "... Round5/reference/src/r5_cpa_pke.o"
	@echo "... Round5/reference/src/r5_cpa_pke.i"
	@echo "... Round5/reference/src/r5_cpa_pke.s"
	@echo "... Round5/reference/src/r5_dem.o"
	@echo "... Round5/reference/src/r5_dem.i"
	@echo "... Round5/reference/src/r5_dem.s"
	@echo "... Round5/reference/src/r5_hash.o"
	@echo "... Round5/reference/src/r5_hash.i"
	@echo "... Round5/reference/src/r5_hash.s"
	@echo "... Round5/reference/src/r5_memory.o"
	@echo "... Round5/reference/src/r5_memory.i"
	@echo "... Round5/reference/src/r5_memory.s"
	@echo "... Round5/reference/src/r5_parameter_sets.o"
	@echo "... Round5/reference/src/r5_parameter_sets.i"
	@echo "... Round5/reference/src/r5_parameter_sets.s"
	@echo "... Round5/reference/src/shake.o"
	@echo "... Round5/reference/src/shake.i"
	@echo "... Round5/reference/src/shake.s"
	@echo "... Round5/reference/src/xef_ref.o"
	@echo "... Round5/reference/src/xef_ref.i"
	@echo "... Round5/reference/src/xef_ref.s"
	@echo "... XKCP/lib/high/KangarooTwelve/KangarooTwelve.o"
	@echo "... XKCP/lib/high/KangarooTwelve/KangarooTwelve.i"
	@echo "... XKCP/lib/high/KangarooTwelve/KangarooTwelve.s"
	@echo "... XKCP/lib/high/Keccak/FIPS202/KeccakHash.o"
	@echo "... XKCP/lib/high/Keccak/FIPS202/KeccakHash.i"
	@echo "... XKCP/lib/high/Keccak/FIPS202/KeccakHash.s"
	@echo "... XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.o"
	@echo "... XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.i"
	@echo "... XKCP/lib/high/Keccak/FIPS202/SimpleFIPS202.s"
	@echo "... XKCP/lib/high/Keccak/KeccakDuplexWidth1600.o"
	@echo "... XKCP/lib/high/Keccak/KeccakDuplexWidth1600.i"
	@echo "... XKCP/lib/high/Keccak/KeccakDuplexWidth1600.s"
	@echo "... XKCP/lib/high/Keccak/KeccakDuplexWidth200.o"
	@echo "... XKCP/lib/high/Keccak/KeccakDuplexWidth200.i"
	@echo "... XKCP/lib/high/Keccak/KeccakDuplexWidth200.s"
	@echo "... XKCP/lib/high/Keccak/KeccakDuplexWidth400.o"
	@echo "... XKCP/lib/high/Keccak/KeccakDuplexWidth400.i"
	@echo "... XKCP/lib/high/Keccak/KeccakDuplexWidth400.s"
	@echo "... XKCP/lib/high/Keccak/KeccakDuplexWidth800.o"
	@echo "... XKCP/lib/high/Keccak/KeccakDuplexWidth800.i"
	@echo "... XKCP/lib/high/Keccak/KeccakDuplexWidth800.s"
	@echo "... XKCP/lib/high/Keccak/KeccakSpongeWidth1600.o"
	@echo "... XKCP/lib/high/Keccak/KeccakSpongeWidth1600.i"
	@echo "... XKCP/lib/high/Keccak/KeccakSpongeWidth1600.s"
	@echo "... XKCP/lib/high/Keccak/KeccakSpongeWidth200.o"
	@echo "... XKCP/lib/high/Keccak/KeccakSpongeWidth200.i"
	@echo "... XKCP/lib/high/Keccak/KeccakSpongeWidth200.s"
	@echo "... XKCP/lib/high/Keccak/KeccakSpongeWidth400.o"
	@echo "... XKCP/lib/high/Keccak/KeccakSpongeWidth400.i"
	@echo "... XKCP/lib/high/Keccak/KeccakSpongeWidth400.s"
	@echo "... XKCP/lib/high/Keccak/KeccakSpongeWidth800.o"
	@echo "... XKCP/lib/high/Keccak/KeccakSpongeWidth800.i"
	@echo "... XKCP/lib/high/Keccak/KeccakSpongeWidth800.s"
	@echo "... XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.o"
	@echo "... XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.i"
	@echo "... XKCP/lib/high/Keccak/PRG/KeccakPRGWidth1600.s"
	@echo "... XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.o"
	@echo "... XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.i"
	@echo "... XKCP/lib/high/Keccak/PRG/KeccakPRGWidth200.s"
	@echo "... XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.o"
	@echo "... XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.i"
	@echo "... XKCP/lib/high/Keccak/PRG/KeccakPRGWidth400.s"
	@echo "... XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.o"
	@echo "... XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.i"
	@echo "... XKCP/lib/high/Keccak/PRG/KeccakPRGWidth800.s"
	@echo "... XKCP/lib/high/Keccak/SP800-185/SP800-185.o"
	@echo "... XKCP/lib/high/Keccak/SP800-185/SP800-185.i"
	@echo "... XKCP/lib/high/Keccak/SP800-185/SP800-185.s"
	@echo "... XKCP/lib/high/Ketje/KetjeJr.o"
	@echo "... XKCP/lib/high/Ketje/KetjeJr.i"
	@echo "... XKCP/lib/high/Ketje/KetjeJr.s"
	@echo "... XKCP/lib/high/Ketje/KetjeMj.o"
	@echo "... XKCP/lib/high/Ketje/KetjeMj.i"
	@echo "... XKCP/lib/high/Ketje/KetjeMj.s"
	@echo "... XKCP/lib/high/Ketje/KetjeMn.o"
	@echo "... XKCP/lib/high/Ketje/KetjeMn.i"
	@echo "... XKCP/lib/high/Ketje/KetjeMn.s"
	@echo "... XKCP/lib/high/Ketje/KetjeSr.o"
	@echo "... XKCP/lib/high/Ketje/KetjeSr.i"
	@echo "... XKCP/lib/high/Ketje/KetjeSr.s"
	@echo "... XKCP/lib/high/Keyak/LakeKeyak.o"
	@echo "... XKCP/lib/high/Keyak/LakeKeyak.i"
	@echo "... XKCP/lib/high/Keyak/LakeKeyak.s"
	@echo "... XKCP/lib/high/Keyak/LunarKeyak.o"
	@echo "... XKCP/lib/high/Keyak/LunarKeyak.i"
	@echo "... XKCP/lib/high/Keyak/LunarKeyak.s"
	@echo "... XKCP/lib/high/Keyak/OceanKeyak.o"
	@echo "... XKCP/lib/high/Keyak/OceanKeyak.i"
	@echo "... XKCP/lib/high/Keyak/OceanKeyak.s"
	@echo "... XKCP/lib/high/Keyak/RiverKeyak.o"
	@echo "... XKCP/lib/high/Keyak/RiverKeyak.i"
	@echo "... XKCP/lib/high/Keyak/RiverKeyak.s"
	@echo "... XKCP/lib/high/Keyak/SeaKeyak.o"
	@echo "... XKCP/lib/high/Keyak/SeaKeyak.i"
	@echo "... XKCP/lib/high/Keyak/SeaKeyak.s"
	@echo "... XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.o"
	@echo "... XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.i"
	@echo "... XKCP/lib/low/KeccakP-1600-times2/FallbackOn1/KeccakP-1600-times2-on1.s"
	@echo "... XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.o"
	@echo "... XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.i"
	@echo "... XKCP/lib/low/KeccakP-1600-times4/FallbackOn1/KeccakP-1600-times4-on1.s"
	@echo "... XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.o"
	@echo "... XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.i"
	@echo "... XKCP/lib/low/KeccakP-1600-times8/FallbackOn1/KeccakP-1600-times8-on1.s"
	@echo "... XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.o"
	@echo "... XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.i"
	@echo "... XKCP/lib/low/KeccakP-1600/Optimized64/KeccakP-1600-opt64.s"
	@echo "... XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.o"
	@echo "... XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.i"
	@echo "... XKCP/lib/low/KeccakP-200/Compact/KeccakP-200-compact.s"
	@echo "... XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.o"
	@echo "... XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.i"
	@echo "... XKCP/lib/low/KeccakP-400/Reference/KeccakP-400-reference.s"
	@echo "... XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.o"
	@echo "... XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.i"
	@echo "... XKCP/lib/low/KeccakP-800/Optimized32/KeccakP-800-opt32.s"
	@echo "... XKCP/lib/low/Ketje/SnP-compliant/KetJr.o"
	@echo "... XKCP/lib/low/Ketje/SnP-compliant/KetJr.i"
	@echo "... XKCP/lib/low/Ketje/SnP-compliant/KetJr.s"
	@echo "... XKCP/lib/low/Ketje/SnP-compliant/KetMj.o"
	@echo "... XKCP/lib/low/Ketje/SnP-compliant/KetMj.i"
	@echo "... XKCP/lib/low/Ketje/SnP-compliant/KetMj.s"
	@echo "... XKCP/lib/low/Ketje/SnP-compliant/KetMn.o"
	@echo "... XKCP/lib/low/Ketje/SnP-compliant/KetMn.i"
	@echo "... XKCP/lib/low/Ketje/SnP-compliant/KetMn.s"
	@echo "... XKCP/lib/low/Ketje/SnP-compliant/KetSr.o"
	@echo "... XKCP/lib/low/Ketje/SnP-compliant/KetSr.i"
	@echo "... XKCP/lib/low/Ketje/SnP-compliant/KetSr.s"
	@echo "... dilithium/ref/PQCgenKAT_sign.o"
	@echo "... dilithium/ref/PQCgenKAT_sign.i"
	@echo "... dilithium/ref/PQCgenKAT_sign.s"
	@echo "... dilithium/ref/aes256ctr.o"
	@echo "... dilithium/ref/aes256ctr.i"
	@echo "... dilithium/ref/aes256ctr.s"
	@echo "... dilithium/ref/fips202.o"
	@echo "... dilithium/ref/fips202.i"
	@echo "... dilithium/ref/fips202.s"
	@echo "... dilithium/ref/ntt.o"
	@echo "... dilithium/ref/ntt.i"
	@echo "... dilithium/ref/ntt.s"
	@echo "... dilithium/ref/packing.o"
	@echo "... dilithium/ref/packing.i"
	@echo "... dilithium/ref/packing.s"
	@echo "... dilithium/ref/poly.o"
	@echo "... dilithium/ref/poly.i"
	@echo "... dilithium/ref/poly.s"
	@echo "... dilithium/ref/polyvec.o"
	@echo "... dilithium/ref/polyvec.i"
	@echo "... dilithium/ref/polyvec.s"
	@echo "... dilithium/ref/reduce.o"
	@echo "... dilithium/ref/reduce.i"
	@echo "... dilithium/ref/reduce.s"
	@echo "... dilithium/ref/rounding.o"
	@echo "... dilithium/ref/rounding.i"
	@echo "... dilithium/ref/rounding.s"
	@echo "... dilithium/ref/sign.o"
	@echo "... dilithium/ref/sign.i"
	@echo "... dilithium/ref/sign.s"
	@echo "... keypair.o"
	@echo "... keypair.i"
	@echo "... keypair.s"
	@echo "... meths/asn1_meth.o"
	@echo "... meths/asn1_meth.i"
	@echo "... meths/asn1_meth.s"
	@echo "... meths/round5_meth.o"
	@echo "... meths/round5_meth.i"
	@echo "... meths/round5_meth.s"
	@echo "... ossl/objects.o"
	@echo "... ossl/objects.i"
	@echo "... ossl/objects.s"
	@echo "... ossl/ossl_compat.o"
	@echo "... ossl/ossl_compat.i"
	@echo "... ossl/ossl_compat.s"
	@echo "... round5_engine.o"
	@echo "... round5_engine.i"
	@echo "... round5_engine.s"
	@echo "... test/engine_check.o"
	@echo "... test/engine_check.i"
	@echo "... test/engine_check.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

